// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DBShared;

#nullable disable

namespace DBShared.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20251003154307_DeleteColumns")]
    partial class DeleteColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TgParse.Models.FishType", b =>
                {
                    b.Property<int>("IdFishType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFishType"));

                    b.Property<string>("FishName")
                        .HasColumnType("text");

                    b.HasKey("IdFishType");

                    b.HasIndex("FishName")
                        .IsUnique();

                    b.ToTable("FishType");
                });

            modelBuilder.Entity("TgParse.Models.FishingPlaceFish", b =>
                {
                    b.Property<int>("IdFishingPlace")
                        .HasColumnType("integer");

                    b.Property<int>("IdFishType")
                        .HasColumnType("integer");

                    b.HasKey("IdFishingPlace", "IdFishType");

                    b.HasIndex("IdFishType");

                    b.ToTable("FishingPlaceFish");
                });

            modelBuilder.Entity("TgParse.Models.FishingPlaceWater", b =>
                {
                    b.Property<int>("IdFishingPlace")
                        .HasColumnType("integer");

                    b.Property<int>("IdWaterType")
                        .HasColumnType("integer");

                    b.HasKey("IdFishingPlace", "IdWaterType");

                    b.HasIndex("IdWaterType");

                    b.ToTable("FishingPlaceWater");
                });

            modelBuilder.Entity("TgParse.Models.FishingPlaces", b =>
                {
                    b.Property<int>("IdFishingPlace")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFishingPlace"));

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("PlaceDescription")
                        .HasColumnType("text");

                    b.Property<string>("PlaceName")
                        .HasColumnType("text");

                    b.HasKey("IdFishingPlace");

                    b.HasIndex("IdFishingPlace")
                        .IsUnique();

                    b.ToTable("FishingPlaces");
                });

            modelBuilder.Entity("TgParse.Models.Regions", b =>
                {
                    b.Property<int>("IdRegions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRegions"));

                    b.Property<string>("RegionName")
                        .HasColumnType("text");

                    b.HasKey("IdRegions");

                    b.HasIndex("RegionName")
                        .IsUnique();

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("TgParse.Models.TgMessages", b =>
                {
                    b.Property<int>("IdTgMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTgMessage"));

                    b.Property<int?>("IdRegion")
                        .HasColumnType("integer");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("MessageText")
                        .HasColumnType("text");

                    b.Property<int?>("PlaceId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.HasKey("IdTgMessage");

                    b.HasIndex("IdRegion");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("PlaceId");

                    b.ToTable("TgMessages");
                });

            modelBuilder.Entity("TgParse.Models.TgPhotos", b =>
                {
                    b.Property<int>("IdTgPhotos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTgPhotos"));

                    b.Property<int>("IdTgMessage")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.HasKey("IdTgPhotos");

                    b.HasIndex("IdTgMessage");

                    b.ToTable("TgPhotos");
                });

            modelBuilder.Entity("TgParse.Models.WaterType", b =>
                {
                    b.Property<int>("IdWaterType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdWaterType"));

                    b.Property<string>("WaterName")
                        .HasColumnType("text");

                    b.HasKey("IdWaterType");

                    b.HasIndex("WaterName")
                        .IsUnique();

                    b.ToTable("WaterType");
                });

            modelBuilder.Entity("TgParse.Models.FishingPlaceFish", b =>
                {
                    b.HasOne("TgParse.Models.FishType", "FishType")
                        .WithMany("FishingPlaceFishes")
                        .HasForeignKey("IdFishType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgParse.Models.FishingPlaces", "FishingPlace")
                        .WithMany("FishingPlaceFishes")
                        .HasForeignKey("IdFishingPlace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishType");

                    b.Navigation("FishingPlace");
                });

            modelBuilder.Entity("TgParse.Models.FishingPlaceWater", b =>
                {
                    b.HasOne("TgParse.Models.FishingPlaces", "FishingPlaces")
                        .WithMany("FishingPlaceWaters")
                        .HasForeignKey("IdFishingPlace")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgParse.Models.WaterType", "WaterType")
                        .WithMany("FishingPlaceWaters")
                        .HasForeignKey("IdWaterType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FishingPlaces");

                    b.Navigation("WaterType");
                });

            modelBuilder.Entity("TgParse.Models.TgMessages", b =>
                {
                    b.HasOne("TgParse.Models.Regions", "Region")
                        .WithMany("Messages")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TgParse.Models.FishingPlaces", "Place")
                        .WithMany("Messages")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Place");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("TgParse.Models.TgPhotos", b =>
                {
                    b.HasOne("TgParse.Models.TgMessages", "Messages")
                        .WithMany("Photos")
                        .HasForeignKey("IdTgMessage")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TgParse.Models.FishType", b =>
                {
                    b.Navigation("FishingPlaceFishes");
                });

            modelBuilder.Entity("TgParse.Models.FishingPlaces", b =>
                {
                    b.Navigation("FishingPlaceFishes");

                    b.Navigation("FishingPlaceWaters");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TgParse.Models.Regions", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TgParse.Models.TgMessages", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("TgParse.Models.WaterType", b =>
                {
                    b.Navigation("FishingPlaceWaters");
                });
#pragma warning restore 612, 618
        }
    }
}
